name: 'Upload to Google Drive'
description: 'Upload files to Google Drive'

branding:
  icon: 'upload-cloud'
  color: 'gray-dark'

inputs:
  skicka-tokencache-json:
    description: 'Content of `~/.skicka.tokencache.json` created by the `skicka` command'
    required: true

  action:
    description: 'The skicka action to perform'
    required: true
  
  args:
    description: 'The commandline args to add'
    required: false

  remove-outdated:
    description: 'Whether to delete files that do not exist locally'
    default: 'true'
    required: false

  google-client-id:
    description: Your Google Drive API client ID
    required: false

  google-client-secret:
    description: Your Google Drive API client secret
    required: false


runs:
  using: docker
  image: Dockerfile
  env:
    SKICKA_TOKENCACHE_JSON: ${{ inputs.skicka-tokencache-json }}
    ACTION: ${{ inputs.action }}
    ARGS: ${{ inputs.args }}
    GOOGLE_CLIENT_ID: ${{ inputs.google-client-id }}
    GOOGLE_CLIENT_SECRET: ${{ inputs.google-client-secret }}
